#server.port=8082
#spring.data.mongodb.uri=mongodb://localhost:27017/user-tracker
#spring.data.mongodb.uri=mongodb://localhost/test
app:
  message: Message sent to the RabbitMQ queue Successfully
server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user-tracker
    #rabbitmq:
    #host: localhost
    #password: guest
    #port: 5672
    #username: guest
    #exchange: user.exchange
    #queue: user.queue
    #routingkey: user.routingkey


  #spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: employee.exchange
    queue: employee.queue
    routingkey: employee.routingkey





